[workspace]
resolver = "3"

members = [
    "app",
    "cli",
    "crates/app_constants",
    "crates/archive_vfs",
    "crates/assets",
    "crates/bit7z",
    "crates/checksum",
    "crates/crashes",
    "crates/explorer",
    "crates/ffi",
    "crates/format_detector",
    "crates/fs",
    "crates/fs_watcher",
    "crates/password",
    "crates/paths",
    "crates/session",
    "crates/shell",
    "crates/system_specs",
    "crates/task",
    "crates/temp",
    "crates/thirdparties/gpui-tray",
    "crates/thirdparties/guise/crates/guise",
    "crates/tray",
    "crates/vfs",
    "executor",
]

exclude = ["crates/thirdparties/guise"]
default-members = ["app"]

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
publish = false
version = "0.1.0"
authors = []
homepage = ""
documentation = ""
keywords = ["archive", "7-zip"]
categories = []
repository = ""

[workspace.dependencies]
anyhow = "1"
app_constants = { path = "crates/app_constants" }
archive_vfs = { path = "crates/archive_vfs" }
assets = { path = "crates/assets" }
async-process = "2.5.0"
async-trait = "*"
bit7z-explorer = { path = "crates/explorer" }
bit7z-ffi = { path = "crates/ffi" }
bit7z-rs = { path = "crates/bit7z" }
checksum = { path = "crates/checksum" }
clap = { version = "4", features = ["derive"] }
const_format = "0.2"
crash-handler = "0.7"
dirs = "6.0"
features = { version = "0.10" }
fs = { path = "crates/fs" }
fs_watcher = { path = "crates/fs_watcher" }
futures = "0.3"
futures-concurrency = "7"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["runtime_shaders"] }
guise-ui = { path = "crates/thirdparties/guise/crates/guise", default-features = false }
human_bytes = "0.4.3"
ignore = "0.4.22"
inventory = "0.3"
jiff = { version = "0.2", features = ["serde"] }
libc = "0.2"
log = "0.4.33"
mach2 = "0.5"
minidumper = "0.9"
parking_lot = "0.12.5"
password = { path = "crates/password" }
pciid-parser = "0.8.1"
rfd = { version = "0.15", default-features = false }
rust-embed = { version = "8.11", features = ["include-exclude"] }
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
session = { path = "crates/session" }
smol = "2.0"
sysinfo = "0.39.6"
system_specs = { path = "crates/system_specs" }
task = { path = "crates/task" }
temp = { path = "crates/temp" }
thiserror = "2.0.19"
util = { git = "https://github.com/zed-industries/zed" }
vfs = { path = "crates/vfs" }
zstd = "0.11"

[workspace.dependencies.windows]
version = "0.61"
features = [
    "Data_Xml_Dom",
    "Foundation_Numerics",
    "Globalization_DateTimeFormatting",
    "Storage_Search",
    "Storage_Streams",
    "System_Threading",
    "UI_Notifications",
    "UI_ViewManagement",
    "Wdk_System_SystemServices",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_DirectManipulation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Imaging",
    "Win32_Graphics_Hlsl",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Security_Credentials",
    "Win32_Security_Cryptography",
    "Win32_Storage_FileSystem",
    "Win32_Storage_Packaging_Appx",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Console",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_DataExchange",
    "Win32_System_IO",
    "Win32_System_JobObjects",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Performance",
    "Win32_System_Pipes",
    "Win32_System_RestartManager",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_Variant",
    "Win32_System_WinRT",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_Pointer",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Media",
]

[workspace.lints.clippy]
almost_complete_range = "allow"
arc_with_non_send_sync = "allow"
borrowed_box = "allow"
dbg_macro = "deny"
let_underscore_future = "allow"
manual_is_multiple_of = "allow"
map_entry = "allow"
module_inception = "allow"
non_canonical_partial_ord_impl = "allow"
reversed_empty_ranges = "allow"
single_range_in_vec_init = "allow"
style = { level = "allow", priority = -1 }
todo = "deny"
type_complexity = "allow"
# Temporarily allow this until we can migrate to the new APIs.
# https://github.com/longbridge/gpui-component/pull/2149
useless_conversion = "allow"

[patch."https://github.com/zed-industries/scap"]
zed-scap = { path = "crates/thirdparties/scap" }

[patch.crates-io]
gpui = { git = "https://github.com/zed-industries/zed", features = ["x11", "wayland", "font-kit"] }
quick-xml = { git = "https://github.com/tafia/quick-xml", tag = "v0.41.0", version = "0.41.0" }

