[package]
name = "cli"
publish.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "bit7z"
path = "src/main.rs"

[dependencies]
bit7z-rs.workspace = true
checksum.workspace = true
clap.workspace = true
format_detector.workspace = true
password.workspace = true
task.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
] }

[lints]
workspace = true