[package]
name = "bit7z-explorer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
gpui.workspace = true
password.workspace = true
session.workspace = true
ui_kit.workspace = true
vfs.workspace = true

[dev-dependencies]
tempfile = "3"
