[package]
name = "explorer-view"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
explorer-model.workspace = true
gpui.workspace = true
#guise-ui.workspace = true
session.workspace = true
vfs.workspace = true

[lints]
workspace = true
