[package]
name = "format_detector"
publish.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
autobins = false

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
serde.workspace = true
futures = { workspace = true }
file-format = { version = "0.29", features = ["reader"] }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true