[package]
name = "executor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "bit7z-executor"
path = "src/main.rs"

[dependencies]
bit7z-explorer.workspace = true
bit7z-rs.workspace = true
clap.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
password.workspace = true
task.workspace = true
#guise-ui.workspace = true

[lints]
workspace = true
