[package]
name = "task"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bit7z-rs.workspace = true
checksum.workspace = true
password.workspace = true
serde.workspace = true
serde_json.workspace = true
temp.workspace = true
thiserror.workspace = true
vfs.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
