[package]
name = "workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
bit7z-rs.workspace = true
explorer.workspace = true
gpui.workspace = true
rfd.workspace = true
session.workspace = true
ui.workspace = true
#platform_title_bar.workspace = true
serde.workspace = true
gpui-kit.workspace = true
serde_json.workspace = true

[lints]
workspace = true
