[package]
name = "workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
app_action.workspace = true
bit7z-rs.workspace = true
checksum.workspace = true
compare.workspace = true
crashes.workspace = true
dunce.workspace = true
explorer.workspace = true
fs_watcher.workspace = true
gpui.workspace = true
multi-workspace-core.workspace = true
password.workspace = true
rfd.workspace = true
session.workspace = true
settings.workspace = true
task.workspace = true
temp.workspace = true
paths.workspace = true
log.workspace = true
tray.workspace = true
ui.workspace = true
vfs.workspace = true
#platform_title_bar.workspace = true
serde.workspace = true
gpui-kit.workspace = true
serde_json.workspace = true

[lints]
workspace = true
